// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmfhgstfclhmtnnmhqgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZmhnc3RmY2xobXRubm1ocWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjQzMjMsImV4cCI6MjA2MTk0MDMyM30.ByO3KvxW-vRwHnEb3u_gkD7UDwV4FfwY60DmIpmqlCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);